# list of queries
query_list = [
    "ai",
    "gaza",
    "harry and meghan",
    "david white on bbc radio cornwall",
    f"uk inflation unexpectedly jumps to 3.6% as food prices rise again",
    "dealer to plead guilty in matthew perry death",
    "fire",
    "best dramas",
    "indecent",
    "Radiohead",
    "Doctor Who",
    "Rugby",
    "Inflation",
    "Artifical intelligence",
    "US vs China chip manufacturing",
    "Europa League",
    "Russia",
    "Trump",
    "Fire",
    "Energy bills increase",
]

natural_queries = [
    "Thenewstoday",
    "msnchester bews",
    "Turkiye",
    "Selfie",
    "Telly",
    "Bestie",
    "BBC",
    "Npc",
    "Iykyk",
    "Skibidi",
    "Delulu",
    "agentic",
    "boujee",
    "overtourism",
    "Rage bait",
    "Lewk",
    "Memeify",
    "nepo baby",
    "Rizz",
    "Brain rot",
]

gibberish_queries = [
    "sfsdsfsd",
    "dhasfd",
    "Ahnahfdsgv",
    "qwgfw ywegdbfehd hyfv",
    "/,./.,.//,@324.//.",
    "0123456789",
    "1i2uq234yt9u4r",
    ".’1;.[l’52q]kotg5rtgyy.;]",
    "h3y, 1t's 0l4m1d3!",
    "00ps-wr0ng_passw0rd",
    "       .x jx n",
    "consiethem",
    "merprithe",
    "slessom",
    "thatio",
    "fleep",
    "discorns",
    "proublesh",
    "consient",
    "naturn",
]

intended_queries = [
    "the news today",
    "manchester news",
    "Turkiye",
    "Harry and Meghan",
    "Doctor Who",
    "Manchester city",
    "Manchester United",
    "Energy bills increase",
    "Dealer to plead guilty in Matthew Perry death",
    "UK inflation unexpectedly jumps to 3.6% as food prices rise again",
    "Trump in the White House",
    "US vs China chip manufacturing",
    "Artificial intelligence",
    "Europa League",
    "best dramas",
    "Telly",
    "Bestie",
    "hey, it's Olamide!",
    "oops, wrong password",
    "delulu",
]

fuzzy_queries = [
    "Thenewstoday",
    "msnchester bews",
    "Turkey",
    "megan and harry",
    "dr who",
    "man city",
    "manu",
    "nrg blls ncrs",
    "matthew perry guilty dealer",
    "uk intlashion unecpeft3rly jumpyd yo 3.6 per cent as food prices rise agin",
    "ttump in the the whit hoyse",
    "us v china chip making",
    "ai",
    "uropa lege",
    "bezt dramz",
    "tellie",
    "best friend",
    "h3y, 1t's 0l4m1d3!",
    "00ps-wr0ng_p4ssw0rd",
    "delusional",
]

fuzzy_gibberish = [
    "sfsdsfsd",
    "dhasfd",
    "Ahnahfdsgv",
    "qwgfw ywegdbfehd hyfv",
    "/,./.,.//,@324.//.",
    "0123456789",
    "1i2uq234yt9u4r",
    ".’1;.[l’52q]kotg5rtgyy.;]",
    "h3y, 1t's 0l4m1d3!",
    "00ps-wr0ng_p4ssw0rd",
    "       .x jx n",
]

# query dict
queries = {
    "query list": query_list,
    "natural queries": natural_queries,
    "gibberish queries": gibberish_queries,
    "intended queries": intended_queries,
    "fuzzy queries": fuzzy_queries,
    "fuzzy gibberish": fuzzy_gibberish,
}
